modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/lexicon/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="minecraft:written_book"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/Lexicon_NEO.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lexicon"
logoFile="logo.png"
credits="The Minecraft Wiki for some graphics and informations"
authors="${mod_authors}"
description='''This mod adds a lexicon to the game that explains almost every aspect of minecraft ingame!'''


[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
type="required"
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
type="required"
versionRange="${mc_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="patchouli"
mandatory=true
type="required"
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"