modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/lexicon/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="minecraft:written_book"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Lexicon/refs/heads/main/versions.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lexicon"
logoFile="logo.png"
credits="The Minecraft Wiki for some graphics and informations"
authors="${mod_authors}"
description='''This mod adds a lexicon to the game that explains almost every aspect of Minecraft ingame!'''

[modproperties.${mod_id}]
configuredBackground="minecraft:textures/block/bookshelf.png"

[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="guideme"
mandatory=true
type="required"
reason="Basemod for Lexicon."
versionRange="[21.5,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="patchouli"
mandatory=false
type="optional"
reason="Basemod for Lexicon."
versionRange="[1.21,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="magmacore"
referralUrl="https://www.curseforge.com/minecraft/mc-mods/magma-core"
reason="Provides basic code and features such as update-checker"
type="required"
versionRange="${magmacore_version_range}"
ordering="AFTER"
side="BOTH"